/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <errno.h>

/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#ifndef _WIN32
#include <unistd.h>
#endif

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif


/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 64
#define YY_END_OF_BUFFER 65
static yyconst short int yy_acclist[256] =
    {   0,
       61,   61,   65,   63,   64,   62,   63,   64,   62,   64,
       40,   63,   64,   63,   64,   41,   63,   64,   63,   64,
       44,   63,   64,   45,   63,   64,   39,   63,   64,   37,
       61,   63,   64,   46,   63,   64,   38,   61,   63,   64,
       61,   63,   64,   35,   63,   64,   59,   61,   63,   64,
       59,   61,   63,   64,    3,   63,   64,   34,   63,   64,
       36,   63,   64,   33,   63,   64,   50,   63,   64,   50,
       61,   63,   64,   47,   63,   64,   48,   63,   64,   50,
       63,   64,   50,   63,   64,   50,   63,   64,   50,   61,
       63,   64,   50,   63,   64,   50,   63,   64,   50,   63,

       64,   50,   63,   64,   50,   63,   64,   50,   63,   64,
       50,   63,   64,   50,   63,   64,   50,   63,   64,   42,
       63,   64,   49,   61,   63,   64,   43,   63,   64,   28,
       57,   58,   25,   52,   29,   61,   61,   61,   61,   61,
       30,   61,   59,   61,   61,    2,   59,   61,   32,   27,
       31,   50,   50,   50,   61,   50,   50,   19,   50,   50,
       50,   50,   50,   15,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   26,   61,   57,   56,   57,   55,
       54,   55,   53,   55,   51,   52,   52,   61,   60,   50,
       50,   50,   50,   18,   50,   50,    7,   50,   50,   50,

       50,   50,   50,   50,   50,   20,   50,   50,   50,   56,
       57,   51,   51,    1,    9,   50,   11,   50,   16,   50,
       50,   50,    5,   50,   24,   50,    8,   50,   50,   50,
       50,   22,   50,    6,   50,   50,    1,   23,   50,   50,
       12,   50,   50,   17,   50,   13,   50,   14,   21,   50,
       10,   50,   50,    4,   50
    } ;

static yyconst short int yy_accept[164] =
    {   0,
        1,    2,    3,    4,    6,    9,   11,   14,   16,   19,
       21,   24,   27,   30,   34,   37,   41,   44,   47,   51,
       55,   58,   61,   64,   67,   70,   74,   77,   80,   83,
       86,   89,   93,   96,   99,  102,  105,  108,  111,  114,
      117,  120,  123,  127,  130,  131,  131,  133,  134,  134,
      134,  134,  134,  135,  137,  138,  139,  140,  141,  143,
      145,  146,  146,  147,  147,  149,  150,  151,  152,  153,
      154,  156,  157,  158,  160,  161,  162,  163,  164,  166,
      167,  168,  169,  170,  171,  172,  173,  174,  175,  177,
      178,  178,  180,  181,  183,  185,  186,  187,  188,  189,

      189,  189,  189,  190,  191,  192,  193,  194,  196,  197,
      199,  200,  201,  202,  203,  204,  205,  206,  208,  209,
      210,  210,  212,  213,  214,  214,  214,  215,  217,  219,
      221,  222,  223,  223,  223,  225,  227,  229,  230,  231,
      232,  234,  236,  237,  238,  238,  238,  240,  241,  242,
      242,  242,  243,  244,  246,  247,  248,  249,  251,  253,
      254,  256,  256
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    1,    1,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   18,   18,    1,   19,   20,
       21,   22,    1,    1,   23,   23,   23,   23,   24,   23,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   26,   25,   25,
       27,    1,   28,    1,   29,    1,   30,   31,   32,   33,

       34,   35,   36,   37,   38,   39,   39,   40,   41,   42,
       43,   39,   39,   44,   45,   46,   47,   48,   49,   50,
       39,   39,   51,   52,   53,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[54] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        3,    1,    1,    1,    1,    1,    4,    4,    1,    1,
        1,    1,    5,    5,    5,    5,    1,    1,    4,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        1,    1,    1
    } ;

static yyconst short int yy_base[176] =
    {   0,
        0,    0,  373,  574,  574,  574,  343,  348,  345,   53,
      574,  574,  316,   95,  574,  102,  109,  106,   99,  118,
      574,  283,  280,  267,  121,  128,  574,  574,  134,  136,
      138,  154,  157,  161,   85,   94,  154,  146,  155,  101,
      175,  574,  106,  574,  574,  272,  262,  574,  258,  249,
      247,    0,  190,  142,  152,  197,  215,  211,  199,    0,
      218,  223,  574,  220,    0,  574,  574,  574,    0,  203,
      222,  211,  217,  218,  226,  232,  237,  244,  246,  252,
      247,  262,  267,  273,  253,  278,  281,  288,  289,  218,
      214,  207,  574,  574,  574,  312,    0,  315,  319,  242,

      248,  331,  322,  308,  313,  319,  320,  328,  329,  366,
      338,  339,  344,  358,  359,  365,  377,  367,  385,  386,
      204,  189,    0,  375,  312,  414,  416,  391,  431,  393,
      407,  401,  180,  178,  409,  415,  438,  439,  416,  423,
      437,  445,  453,  461,  153,  158,  446,  460,  574,  130,
       97,  467,  465,  472,  574,  474,  574,  475,  481,  483,
      486,  574,  533,  536,  538,  543,   51,  545,  550,  552,
      557,  559,  561,  566,  568
    } ;

static yyconst short int yy_def[176] =
    {   0,
      162,    1,  162,  162,  162,  162,  162,  163,  162,  162,
      162,  162,  164,  162,  162,   14,  162,  162,   14,   14,
      162,  162,  162,  162,  165,  165,  162,  162,  165,  165,
      165,  165,  165,  165,   33,   33,   33,   33,   33,   33,
       33,  162,   14,  162,  162,  163,  166,  162,  162,  162,
      162,  167,  168,  162,  162,  162,   14,  162,  162,   20,
      162,  169,  162,  162,   20,  162,  162,  162,  170,   33,
      170,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,  162,  171,
      166,  166,  162,  162,  162,  172,  173,  168,  162,  169,

      174,  169,  162,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
      171,  166,  175,  172,  174,  174,  169,   33,   33,   33,
       33,   33,  162,  162,   33,   33,   33,   33,   33,   33,
       33,   33,   33,  174,  162,  162,   33,   33,  162,  162,
      162,   33,   33,   33,  162,   33,  162,   33,   33,   33,
       33,    0,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162
    } ;

static yyconst short int yy_nxt[628] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   25,   25,   27,   28,    4,   25,
       29,   30,   31,   32,   33,   25,   25,   34,   25,   25,
       35,   36,   25,   37,   38,   39,   25,   40,   41,   25,
       42,   43,   44,   49,   49,   96,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   50,   50,   50,   50,   49,
       49,   49,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,

       51,   51,   51,   49,   49,   49,   54,  157,   55,   56,
       55,   57,   57,   55,   81,   59,   62,   55,   58,   60,
       55,   63,   55,   70,   64,   61,   61,   70,   58,   55,
       86,   70,   58,  157,   65,   65,   70,   69,   69,   55,
       82,   55,   58,   87,   71,   71,   55,   70,   64,   69,
       69,   69,   69,   69,   69,   69,   69,   89,   99,   99,
       55,  155,   69,  155,   69,   55,   69,   55,   99,   99,
       71,   71,   73,   69,   69,   70,   72,   69,   69,   55,
       74,  149,   69,   70,   70,   69,   76,   83,   70,   69,
      149,   84,   70,   75,   92,   79,   70,   70,   85,   77,

       70,   70,   80,   78,   70,   55,   97,   97,   55,  122,
       55,   88,   92,   61,   61,   99,   99,   70,   97,   92,
       58,   70,   55,  122,   55,  101,   55,   99,   99,   55,
       58,   55,   70,  102,   61,   61,  103,  103,   71,   71,
       70,   58,  103,  103,  101,   70,  105,   70,   55,   70,
      101,   58,  102,  104,   95,   70,   94,   70,  126,   70,
       70,   70,   55,   70,   70,   93,   70,   92,   70,   55,
      106,  107,   70,   70,   70,   70,   70,   90,   70,   70,
      108,   70,   70,   70,  111,  109,   70,   68,   70,   70,
       70,   70,   70,   70,   70,   70,  113,  110,   70,  117,

       67,  112,   70,   66,   70,   99,   99,   70,   70,   70,
       70,  114,  115,   70,  162,   70,  116,   70,  119,   70,
       70,  118,  126,   70,   70,  120,   52,   70,  123,  123,
       70,   97,   97,  101,   70,   99,   99,   70,  103,  103,
      123,  102,   70,   97,  103,  103,  127,  128,   70,   70,
       70,   48,  130,   47,   70,   70,  129,   70,   70,   70,
      132,   70,   70,   45,  131,   70,   70,   70,   70,  133,
       70,   70,  162,   70,   70,   70,  134,  162,  136,  135,
       70,   70,  162,  137,   70,   70,   70,   70,   70,  162,
       70,  123,  123,  162,   70,   70,   70,  138,  162,  162,

       70,   70,  140,  123,   70,  139,   70,   70,   70,   70,
      141,   70,   70,   70,   70,   70,  162,  142,  101,   70,
       70,  162,   70,   70,  126,  143,  102,   70,   70,  144,
       70,   70,   70,   70,  145,   70,   70,   70,   70,   70,
      147,  146,  151,   70,   70,   70,  148,   70,  150,   70,
      162,   70,   70,   70,  162,   70,  162,   70,   70,  152,
       70,   70,   70,  162,  153,   70,   70,   70,   70,   70,
      162,  126,  162,   70,   70,   70,  162,   70,  162,   70,
       70,   70,   70,   70,   70,   70,  154,   70,   70,   70,
      162,   70,   70,  162,   70,   70,   70,  156,  162,   70,

      159,   70,   70,   70,   70,  162,   70,   70,  158,   70,
       70,   70,   70,   70,   70,   70,  160,   70,   70,  162,
       70,   70,  162,   70,  161,   70,  162,   70,   70,   70,
      162,  162,   70,   46,  162,   46,   46,   46,   53,  162,
       53,   70,   70,   91,  162,   91,   91,   91,   98,   98,
      100,  100,  100,  100,  100,   69,   69,  121,  162,  121,
      121,  121,  124,  124,   97,   97,  125,  125,  125,  125,
      125,  123,  123,    3,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,

      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  162
    } ;

static yyconst short int yy_chk[628] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   10,   10,  167,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,

       10,   10,   10,   10,   10,   10,   14,  151,   14,   14,
       19,   14,   14,   16,   35,   16,   18,   43,   14,   16,
       17,   18,   17,   36,   19,   17,   17,   35,   14,   20,
       40,   35,   17,  150,   20,   20,   36,   25,   25,   26,
       36,   26,   17,   40,   26,   26,   14,   40,   19,   25,
       29,   29,   30,   30,   31,   31,   26,   43,   54,   54,
       17,  146,   29,  145,   30,   32,   31,   32,   55,   55,
       32,   32,   30,   33,   33,   38,   29,   34,   34,   26,
       31,  134,   32,   37,   39,   33,   33,   37,   38,   34,
      133,   38,   38,   32,  122,   34,   37,   39,   39,   33,

       37,   39,   34,   33,   41,   32,   53,   53,   56,  121,
       56,   41,   92,   56,   56,   59,   59,   41,   53,   91,
       56,   41,   58,   90,   58,   62,   57,   58,   58,   61,
       56,   61,   70,   62,   61,   61,   64,   64,   71,   71,
       72,   61,   64,   64,  100,   70,   73,   74,   56,   70,
      101,   61,  100,   72,   51,   75,   50,   72,  101,   73,
       74,   76,   58,   73,   74,   49,   77,   47,   75,   61,
       75,   76,   75,   78,   76,   79,   81,   46,   76,   77,
       77,   80,   85,   77,   81,   78,   78,   24,   79,   81,
       78,   82,   79,   81,   80,   85,   83,   80,   80,   85,

       23,   82,   84,   22,   82,   89,   89,   86,   82,   83,
       87,   83,   83,   83,  125,   84,   84,   88,   87,   84,
       86,   86,  125,   87,   86,   88,   13,   87,   96,   96,
       88,   98,   98,  102,   88,   99,   99,  104,  103,  103,
       96,  102,  105,   98,  103,  103,  102,  104,  106,  107,
      104,    9,  106,    8,  104,  105,  105,  108,  109,  105,
      109,  106,  107,    7,  107,  106,  107,  111,  112,  110,
      108,  109,    3,  113,  108,  109,  110,    0,  112,  111,
      111,  112,    0,  113,  111,  112,  113,  114,  115,    0,
      113,  124,  124,    0,  116,  110,  118,  114,    0,    0,

      114,  115,  116,  124,  114,  115,  117,  116,  110,  118,
      117,  116,  110,  118,  119,  120,  126,  119,  127,  117,
      128,    0,  130,  117,  126,  120,  127,  119,  120,  126,
      132,  119,  120,  128,  129,  130,  131,  128,  135,  130,
      131,  129,  138,  132,  136,  139,  132,  132,  137,  131,
        0,  135,  140,  131,    0,  135,    0,  136,  139,  139,
      129,  136,  139,  144,  140,  140,  141,  137,  138,  140,
        0,  144,    0,  129,  142,  147,    0,  129,    0,  141,
      137,  138,  143,  141,  137,  138,  143,  142,  147,  148,
        0,  142,  147,    0,  153,  143,  152,  148,    0,  143,

      153,  154,  148,  156,  158,    0,  148,  153,  152,  152,
      159,  153,  160,  152,  154,  161,  156,  158,  154,    0,
      156,  158,    0,  159,  160,  160,    0,  159,  161,  160,
        0,    0,  161,  163,    0,  163,  163,  163,  164,    0,
      164,  165,  165,  166,    0,  166,  166,  166,  168,  168,
      169,  169,  169,  169,  169,  170,  170,  171,    0,  171,
      171,  171,  172,  172,  173,  173,  174,  174,  174,  174,
      174,  175,  175,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,

      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  162
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "myLEX.l"
#define INITIAL 0
//this file was made by:
//Kfir Rahamim 203426721
//Hen Dahan 312585953	
//Bar Piglanski 204590384
#line 6 "myLEX.l"
extern int yylineno;
#line 605 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 9 "myLEX.l"

#line 769 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 163 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 574 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 10 "myLEX.l"
{return COMMENTS;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 11 "myLEX.l"
{return ILLEGAL_COMMENT;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 12 "myLEX.l"
{return EOS;}//End Of Statement
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 13 "myLEX.l"
{return FUNCTION;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 14 "myLEX.l"
{return MAIN;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 15 "myLEX.l"
{return TYPE_VOID;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 16 "myLEX.l"
{return TYPE_INT;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 17 "myLEX.l"
{return TYPE_REAL;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 18 "myLEX.l"
{return TYPE_BOOL;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 19 "myLEX.l"
{return TYPE_STRING;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 20 "myLEX.l"
{return TYPE_CHAR;}	
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 21 "myLEX.l"
{return TYPE_P_INT;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 22 "myLEX.l"
{return TYPE_P_CHAR;}//pointer
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 23 "myLEX.l"
{return TYPE_P_REAL;}//pointer
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 24 "myLEX.l"
{return IF;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 25 "myLEX.l"
{return ELSE;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 26 "myLEX.l"
{return WHILE;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 27 "myLEX.l"
{return FOR;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 28 "myLEX.l"
{return DO;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 29 "myLEX.l"
{return VAR;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 30 "myLEX.l"
{return RETURN;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 31 "myLEX.l"
{return TRUE;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 32 "myLEX.l"
{return FALSE;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 33 "myLEX.l"
{return NULL;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 34 "myLEX.l"
{return AND;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 35 "myLEX.l"
{return OR;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 36 "myLEX.l"
{return EQUALIVATION;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 37 "myLEX.l"
{return NOTEQUAL;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 38 "myLEX.l"
{return PLUSONE;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 39 "myLEX.l"
{return MINUSONE;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 40 "myLEX.l"
{return BIGGER_EQ;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 41 "myLEX.l"
{return SMALLER_EQ;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 42 "myLEX.l"
{return BIGGER;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 43 "myLEX.l"
{return SMALLER;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 44 "myLEX.l"
{return DIVIDED;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 45 "myLEX.l"
{return EQUAL;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 46 "myLEX.l"
{return PLUS;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 47 "myLEX.l"
{return MINUS;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 48 "myLEX.l"
{return MULTIPLY;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 49 "myLEX.l"
{return NOT;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 50 "myLEX.l"
{return ADDRESS_OF;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 51 "myLEX.l"
{return SCB;}//Start Code Block
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 52 "myLEX.l"
{return ECB;}//End Code Block
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 53 "myLEX.l"
{return LP;}//Left Parameter
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 54 "myLEX.l"
{return RP;}//Rigth Parameter
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 55 "myLEX.l"
{return COMMA;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 56 "myLEX.l"
{return BSI;}//Begin String Index
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 57 "myLEX.l"
{return ESI;}//End String Index
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 58 "myLEX.l"
{return DLOS;}//Declared Lengh Of String |s|
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 60 "myLEX.l"
{return ID;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 62 "myLEX.l"
{return ILLEGAL_POINTER;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 63 "myLEX.l"
{return POINTER;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 65 "myLEX.l"
{return CHAR_lowercase;}//not shore need a check!!!!
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 66 "myLEX.l"
{return CHAR_uppercase;}//not shore need a check!!!!
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 67 "myLEX.l"
{return CHAR;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 69 "myLEX.l"
{return INVALID_STRING;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 70 "myLEX.l"
{return STRING;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 71 "myLEX.l"
{return EMPTY_STRING;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 76 "myLEX.l"
{return DEC_INT;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 77 "myLEX.l"
{return HEX_INT;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 78 "myLEX.l"
{return REAL;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 81 "myLEX.l"
;//ignores tab and spaces.
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 82 "myLEX.l"
return yytext[0];
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 83 "myLEX.l"
ECHO;
	YY_BREAK
#line 1180 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 163 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 163 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 162);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef _WIN32
#include <unistd.h>
#else
#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 83 "myLEX.l"
