#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from my_YACC.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "my_YACC.y"

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
extern int yylex();
extern int yylineno;

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"
#ifndef YY_USE_CLASS
# ifndef YYSTYPE
#  define YYSTYPE int
#  define YYSTYPE_IS_TRIVIAL 1
# endif
#endif

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	FUNCTION	258
#define	TYPE_BOOL	259
#define	TYPE_STRING	260
#define	TYPE_VOID	261
#define	MAIN	262
#define	TYPE_INT	263
#define	TYPE_CHAR	264
#define	TYPE_REAL	265
#define	TYPE_P_INT	266
#define	TYPE_P_CHAR	267
#define	TYPE_P_REAL	268
#define	EOS	269
#define	ID	270
#define	IF	271
#define	ELSE	272
#define	WHILE	273
#define	FOR	274
#define	DO	275
#define	VAR	276
#define	RETURN	277
#define	TRUE	278
#define	FALSE	279
#define	NULL	280
#define	AND	281
#define	OR	282
#define	EQUALIVATION	283
#define	NOTEQUAL	284
#define	PLUSONE	285
#define	MINUSONE	286
#define	BIGGER_EQ	287
#define	SMALLER_EQ	288
#define	BIGGER	289
#define	SMALLER	290
#define	DIVIDED	291
#define	EQUAL	292
#define	PLUS	293
#define	MINUS	294
#define	MULTIPLY	295
#define	NOT	296
#define	ADDRESS_OF	297
#define	SCB	298
#define	ECB	299
#define	LP	300
#define	RP	301
#define	COMMA	302
#define	BSI	303
#define	ESI	304
#define	LENGTH	305
#define	CHAR_lowercase	306
#define	CHAR_uppercase	307
#define	CHAR	308
#define	INVALID_STRING	309
#define	STRING	310
#define	EMPTY_STRING	311
#define	DEC_INT	312
#define	HEX_INT	313
#define	REAL	314


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int FUNCTION;
static const int TYPE_BOOL;
static const int TYPE_STRING;
static const int TYPE_VOID;
static const int MAIN;
static const int TYPE_INT;
static const int TYPE_CHAR;
static const int TYPE_REAL;
static const int TYPE_P_INT;
static const int TYPE_P_CHAR;
static const int TYPE_P_REAL;
static const int EOS;
static const int ID;
static const int IF;
static const int ELSE;
static const int WHILE;
static const int FOR;
static const int DO;
static const int VAR;
static const int RETURN;
static const int TRUE;
static const int FALSE;
static const int NULL;
static const int AND;
static const int OR;
static const int EQUALIVATION;
static const int NOTEQUAL;
static const int PLUSONE;
static const int MINUSONE;
static const int BIGGER_EQ;
static const int SMALLER_EQ;
static const int BIGGER;
static const int SMALLER;
static const int DIVIDED;
static const int EQUAL;
static const int PLUS;
static const int MINUS;
static const int MULTIPLY;
static const int NOT;
static const int ADDRESS_OF;
static const int SCB;
static const int ECB;
static const int LP;
static const int RP;
static const int COMMA;
static const int BSI;
static const int ESI;
static const int LENGTH;
static const int CHAR_lowercase;
static const int CHAR_uppercase;
static const int CHAR;
static const int INVALID_STRING;
static const int STRING;
static const int EMPTY_STRING;
static const int DEC_INT;
static const int HEX_INT;
static const int REAL;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,FUNCTION=258
	,TYPE_BOOL=259
	,TYPE_STRING=260
	,TYPE_VOID=261
	,MAIN=262
	,TYPE_INT=263
	,TYPE_CHAR=264
	,TYPE_REAL=265
	,TYPE_P_INT=266
	,TYPE_P_CHAR=267
	,TYPE_P_REAL=268
	,EOS=269
	,ID=270
	,IF=271
	,ELSE=272
	,WHILE=273
	,FOR=274
	,DO=275
	,VAR=276
	,RETURN=277
	,TRUE=278
	,FALSE=279
	,NULL=280
	,AND=281
	,OR=282
	,EQUALIVATION=283
	,NOTEQUAL=284
	,PLUSONE=285
	,MINUSONE=286
	,BIGGER_EQ=287
	,SMALLER_EQ=288
	,BIGGER=289
	,SMALLER=290
	,DIVIDED=291
	,EQUAL=292
	,PLUS=293
	,MINUS=294
	,MULTIPLY=295
	,NOT=296
	,ADDRESS_OF=297
	,SCB=298
	,ECB=299
	,LP=300
	,RP=301
	,COMMA=302
	,BSI=303
	,ESI=304
	,LENGTH=305
	,CHAR_lowercase=306
	,CHAR_uppercase=307
	,CHAR=308
	,INVALID_STRING=309
	,STRING=310
	,EMPTY_STRING=311
	,DEC_INT=312
	,HEX_INT=313
	,REAL=314


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::FUNCTION=258;
const int YY_parse_CLASS::TYPE_BOOL=259;
const int YY_parse_CLASS::TYPE_STRING=260;
const int YY_parse_CLASS::TYPE_VOID=261;
const int YY_parse_CLASS::MAIN=262;
const int YY_parse_CLASS::TYPE_INT=263;
const int YY_parse_CLASS::TYPE_CHAR=264;
const int YY_parse_CLASS::TYPE_REAL=265;
const int YY_parse_CLASS::TYPE_P_INT=266;
const int YY_parse_CLASS::TYPE_P_CHAR=267;
const int YY_parse_CLASS::TYPE_P_REAL=268;
const int YY_parse_CLASS::EOS=269;
const int YY_parse_CLASS::ID=270;
const int YY_parse_CLASS::IF=271;
const int YY_parse_CLASS::ELSE=272;
const int YY_parse_CLASS::WHILE=273;
const int YY_parse_CLASS::FOR=274;
const int YY_parse_CLASS::DO=275;
const int YY_parse_CLASS::VAR=276;
const int YY_parse_CLASS::RETURN=277;
const int YY_parse_CLASS::TRUE=278;
const int YY_parse_CLASS::FALSE=279;
const int YY_parse_CLASS::NULL=280;
const int YY_parse_CLASS::AND=281;
const int YY_parse_CLASS::OR=282;
const int YY_parse_CLASS::EQUALIVATION=283;
const int YY_parse_CLASS::NOTEQUAL=284;
const int YY_parse_CLASS::PLUSONE=285;
const int YY_parse_CLASS::MINUSONE=286;
const int YY_parse_CLASS::BIGGER_EQ=287;
const int YY_parse_CLASS::SMALLER_EQ=288;
const int YY_parse_CLASS::BIGGER=289;
const int YY_parse_CLASS::SMALLER=290;
const int YY_parse_CLASS::DIVIDED=291;
const int YY_parse_CLASS::EQUAL=292;
const int YY_parse_CLASS::PLUS=293;
const int YY_parse_CLASS::MINUS=294;
const int YY_parse_CLASS::MULTIPLY=295;
const int YY_parse_CLASS::NOT=296;
const int YY_parse_CLASS::ADDRESS_OF=297;
const int YY_parse_CLASS::SCB=298;
const int YY_parse_CLASS::ECB=299;
const int YY_parse_CLASS::LP=300;
const int YY_parse_CLASS::RP=301;
const int YY_parse_CLASS::COMMA=302;
const int YY_parse_CLASS::BSI=303;
const int YY_parse_CLASS::ESI=304;
const int YY_parse_CLASS::LENGTH=305;
const int YY_parse_CLASS::CHAR_lowercase=306;
const int YY_parse_CLASS::CHAR_uppercase=307;
const int YY_parse_CLASS::CHAR=308;
const int YY_parse_CLASS::INVALID_STRING=309;
const int YY_parse_CLASS::STRING=310;
const int YY_parse_CLASS::EMPTY_STRING=311;
const int YY_parse_CLASS::DEC_INT=312;
const int YY_parse_CLASS::HEX_INT=313;
const int YY_parse_CLASS::REAL=314;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		220
#define	YYFLAG		-32768
#define	YYNTBASE	60

#define YYTRANSLATE(x) ((unsigned)(x) <= 314 ? yytranslate[x] : 98)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45,
    46,    47,    48,    49,    50,    51,    52,    53,    54,    55,
    56,    57,    58,    59
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     4,    12,    14,    16,    17,    26,    28,    37,
    42,    48,    52,    54,    59,    62,    63,    67,    71,    75,
    79,    83,    85,    89,    93,    97,   101,   105,   109,   113,
   116,   120,   122,   124,   127,   130,   132,   134,   136,   138,
   140,   142,   144,   149,   151,   153,   155,   157,   159,   161,
   163,   165,   167,   169,   171,   175,   179,   182,   185,   186,
   191,   195,   200,   207,   214,   223,   225,   229,   233,   239,
   241,   243,   245,   247,   249,   251,   253,   255,   257,   261,
   266,   269,   272,   273,   275,   277,   279,   281,   283,   285,
   289,   294,   296,   300,   306,   314,   322,   324,   332,   344,
   347,   350,   353,   356,   361,   365
};

static const short yyrhs[] = {    62,
     0,    61,     0,     3,     6,     7,    45,    69,    46,    67,
     0,    65,     0,    63,     0,     0,     3,     6,    64,    45,
    69,    46,    66,    62,     0,    15,     0,     3,    86,    64,
    45,    69,    46,    67,    62,     0,    43,    80,    89,    44,
     0,    43,    80,    89,    87,    44,     0,    64,    47,    68,
     0,    64,     0,    86,    68,    14,    69,     0,    86,    68,
     0,     0,    70,    34,    70,     0,    70,    32,    70,     0,
    70,    35,    70,     0,    70,    33,    70,     0,    70,    28,
    70,     0,    88,     0,    70,    29,    70,     0,    70,    38,
    70,     0,    70,    39,    70,     0,    70,    40,    70,     0,
    70,    36,    70,     0,    70,    26,    70,     0,    70,    27,
    70,     0,    41,    70,     0,    45,    70,    46,     0,    72,
     0,    71,     0,    42,    70,     0,    40,    70,     0,    78,
     0,    64,     0,    76,     0,    77,     0,    85,     0,    73,
     0,    79,     0,    72,    48,    70,    49,     0,    25,     0,
    57,     0,    58,     0,    59,     0,    23,     0,    24,     0,
    52,     0,    51,     0,    53,     0,    74,     0,    75,     0,
    50,    85,    50,     0,    50,    64,    50,     0,    80,    81,
     0,    80,    82,     0,     0,    21,    86,    84,    14,     0,
     5,    83,    14,     0,    64,    48,    70,    49,     0,    83,
    47,    64,    48,    70,    49,     0,    85,    37,    64,    48,
    70,    49,     0,    83,    47,    64,    48,    70,    49,    37,
    85,     0,    64,     0,    64,    47,    84,     0,    64,    37,
    70,     0,    64,    37,    70,    47,    84,     0,    55,     0,
    56,     0,     8,     0,     9,     0,    10,     0,     4,     0,
    11,     0,    12,     0,    13,     0,    22,    72,    14,     0,
    70,    37,    70,    14,     0,    89,    90,     0,    89,    92,
     0,     0,    93,     0,    94,     0,    65,     0,    63,     0,
    91,     0,    66,     0,    64,    45,    46,     0,    64,    45,
    92,    46,     0,    70,     0,    92,    47,    70,     0,    16,
    45,    70,    46,    90,     0,    16,    45,    70,    46,    90,
    17,    90,     0,    18,    45,    70,    46,    43,    89,    44,
     0,    95,     0,    20,    67,    18,    45,    70,    46,    14,
     0,    19,    45,    97,    14,    70,    14,    96,    46,    43,
    89,    44,     0,    64,    30,     0,    30,    64,     0,    64,
    31,     0,    31,    64,     0,    78,    64,    37,    57,     0,
    64,    37,    57,     0,    64,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    25,    26,    28,    30,    31,    32,    37,    40,    42,    44,
    46,    52,    53,    56,    57,    58,    60,    61,    62,    63,
    64,    65,    66,    67,    68,    69,    70,    71,    72,    73,
    74,    75,    76,    77,    82,    85,    86,    87,    88,    89,
    90,    91,    92,    97,   100,   101,   103,   104,   106,   108,
   109,   110,   113,   114,   117,   118,   120,   121,   122,   124,
   127,   129,   130,   131,   132,   135,   136,   137,   138,   141,
   142,   148,   149,   150,   151,   152,   153,   154,   160,   163,
   166,   167,   168,   170,   171,   172,   173,   174,   175,   182,
   183,   185,   186,   189,   190,   194,   195,   196,   198,   200,
   201,   202,   203,   205,   206,   207
};

static const char * const yytname[] = {   "$","error","$illegal.","FUNCTION",
"TYPE_BOOL","TYPE_STRING","TYPE_VOID","MAIN","TYPE_INT","TYPE_CHAR","TYPE_REAL",
"TYPE_P_INT","TYPE_P_CHAR","TYPE_P_REAL","EOS","ID","IF","ELSE","WHILE","FOR",
"DO","VAR","RETURN","TRUE","FALSE","NULL","AND","OR","EQUALIVATION","NOTEQUAL",
"PLUSONE","MINUSONE","BIGGER_EQ","SMALLER_EQ","BIGGER","SMALLER","DIVIDED","EQUAL",
"PLUS","MINUS","MULTIPLY","NOT","ADDRESS_OF","SCB","ECB","LP","RP","COMMA","BSI",
"ESI","LENGTH","CHAR_lowercase","CHAR_uppercase","CHAR","INVALID_STRING","STRING",
"EMPTY_STRING","DEC_INT","HEX_INT","REAL","main_program","main_func","code",
"void_function","id","function","void_code_block","code_block","args","parameter_list",
"exp","pointer_id","literal","null","int","real","bool","char","number","string_length",
"var_dec","premitive_dec","string_dec","string_assign_op","premitive_assign_op",
"string","type","return","assignment_statment","body","body_","function_call",
"exp_list","ifelse","loop","for_loop","inc_dec","loop_i_dec",""
};
#endif

static const short yyr1[] = {     0,
    60,    60,    61,    62,    62,    62,    63,    64,    65,    66,
    67,    68,    68,    69,    69,    69,    70,    70,    70,    70,
    70,    70,    70,    70,    70,    70,    70,    70,    70,    70,
    70,    70,    70,    70,    71,    72,    72,    72,    72,    72,
    72,    72,    72,    73,    74,    74,    75,    76,    76,    77,
    77,    77,    78,    78,    79,    79,    80,    80,    80,    81,
    82,    83,    83,    83,    83,    84,    84,    84,    84,    85,
    85,    86,    86,    86,    86,    86,    86,    86,    87,    88,
    89,    89,    89,    90,    90,    90,    90,    90,    90,    91,
    91,    92,    92,    93,    93,    94,    94,    94,    95,    96,
    96,    96,    96,    97,    97,    97
};

static const short yyr2[] = {     0,
     1,     1,     7,     1,     1,     0,     8,     1,     8,     4,
     5,     3,     1,     4,     2,     0,     3,     3,     3,     3,
     3,     1,     3,     3,     3,     3,     3,     3,     3,     2,
     3,     1,     1,     2,     2,     1,     1,     1,     1,     1,
     1,     1,     4,     1,     1,     1,     1,     1,     1,     1,
     1,     1,     1,     1,     3,     3,     2,     2,     0,     4,
     3,     4,     6,     6,     8,     1,     3,     3,     5,     1,
     1,     1,     1,     1,     1,     1,     1,     1,     3,     4,
     2,     2,     0,     1,     1,     1,     1,     1,     1,     3,
     4,     1,     3,     5,     7,     7,     1,     7,    11,     2,
     2,     2,     2,     4,     3,     1
};

static const short yydefact[] = {     6,
     0,     2,     1,     5,     4,    75,     0,    72,    73,    74,
    76,    77,    78,     0,     0,     8,     0,     0,    16,    16,
    16,     0,     0,     0,     0,     0,    13,    15,     0,     0,
    59,     3,     0,    16,    59,     6,     6,    83,    12,    14,
    83,     0,     7,     9,     0,     0,    57,    58,     0,     0,
     0,    70,    71,     0,     0,     0,     0,     0,     0,     0,
     0,     0,    48,    49,    44,     0,     0,     0,     0,     0,
    51,    50,    52,    45,    46,    47,    87,    37,    86,    89,
    92,    33,    32,    41,    53,    54,    38,    39,    36,    42,
    40,     0,    22,    81,    88,    82,    84,    85,    97,    10,
     0,    61,     0,     0,    66,     0,     0,     0,     0,     0,
    37,     0,    35,    30,    34,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,    11,     0,     0,     0,     0,     0,     0,
    60,     0,     0,   106,     0,     0,     0,    79,    31,    56,
    55,    90,     0,    28,    29,    21,    23,    18,    20,    17,
    19,    27,     0,    24,    25,    26,     0,    93,    62,     0,
     0,    68,    67,     0,     0,     0,     0,     0,     0,    91,
    80,    43,     0,     0,     0,     0,    94,    83,   105,     0,
     0,     0,    63,    64,    69,     0,     0,   104,     0,     0,
     0,    95,    96,     0,     0,     0,     0,    98,    65,   101,
   103,   100,   102,     0,    83,     0,    99,     0,     0,     0
};

static const short yydefgoto[] = {   218,
     2,     3,    77,   111,    79,    80,    32,    28,    22,    81,
    82,    83,    84,    85,    86,    87,    88,    89,    90,    38,
    47,    48,    55,   106,    91,    23,    92,    93,    49,    94,
    95,    96,    97,    98,    99,   207,   146
};

static const short yypact[] = {     6,
   229,-32768,-32768,-32768,-32768,-32768,    71,-32768,-32768,-32768,
-32768,-32768,-32768,    77,    37,-32768,    44,    50,   108,   108,
   108,    59,    77,    60,    81,    70,    63,   114,    88,    70,
-32768,-32768,    77,   108,-32768,   129,   129,    12,-32768,-32768,
    12,   274,-32768,-32768,    -9,   108,-32768,-32768,   161,   207,
    77,-32768,-32768,    96,    46,   109,    77,   100,   102,   106,
    70,   343,-32768,-32768,-32768,   320,   320,   320,   320,    -9,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,   107,-32768,-32768,
   556,-32768,   105,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,   110,-32768,-32768,-32768,   118,-32768,-32768,-32768,-32768,
   320,-32768,    77,    77,    -8,   141,   320,   320,    -1,   138,
-32768,    14,    74,-32768,-32768,   496,   116,   119,    84,   320,
   320,   320,   320,   320,   320,   320,   320,   320,   320,   320,
   320,   320,   320,-32768,   320,   408,   120,   122,   320,    77,
-32768,   511,   526,   134,    77,   143,   127,-32768,-32768,-32768,
-32768,-32768,   -24,   136,   136,   123,   123,   123,   123,   123,
   123,    74,   377,    54,    54,    74,   426,   556,-32768,   320,
   320,   480,-32768,    16,   131,   125,   150,   320,   320,-32768,
-32768,-32768,   444,   462,    77,   107,   171,-32768,-32768,   137,
   393,   541,   154,-32768,-32768,    16,   252,-32768,   -10,   179,
   -31,-32768,-32768,    77,    77,    57,   149,-32768,-32768,-32768,
-32768,-32768,-32768,   153,-32768,   297,-32768,   199,   200,-32768
};

static const short yypgoto[] = {-32768,
-32768,    67,     4,    -7,    18,   176,     0,   174,    64,   -56,
-32768,   146,-32768,-32768,-32768,-32768,-32768,   112,-32768,   180,
-32768,-32768,-32768,  -137,   -43,     7,-32768,-32768,   -40,  -159,
-32768,   115,-32768,-32768,-32768,-32768,-32768
};


#define	YYLAST		596


static const short yytable[] = {    17,
    50,    56,   173,     4,    16,    16,    18,    14,     1,   113,
   114,   115,   116,    16,   187,    27,    45,     5,    42,   204,
   205,   180,   135,    52,    53,    27,   118,   148,   139,    37,
    16,    58,    46,    59,    60,    61,   202,    54,   140,     4,
     4,    78,    78,    17,   136,    52,    53,   195,    14,   105,
   142,   143,    57,     5,     5,    74,    75,    76,    35,   102,
   110,   133,   117,   154,   155,   156,   157,   158,   159,   160,
   161,   162,   163,   164,   165,   166,   167,    15,   168,   120,
   121,    19,   172,    24,    25,    16,   212,   213,    20,   128,
   129,    16,   103,   132,    21,   137,   138,    40,    16,   120,
   121,   144,    43,    44,    26,    29,    63,    64,    65,    33,
   129,     6,    31,   183,   184,     8,     9,    10,    11,    12,
    13,   191,   192,    66,    67,    68,    30,    34,    69,   152,
    35,    42,   105,    70,    71,    72,    73,   177,    52,    53,
    74,    75,    76,   101,   107,   104,   108,   197,   120,   121,
   109,   119,   133,   134,   141,   147,   178,   209,   128,   129,
   130,   131,   132,    42,   135,   150,   186,   170,   151,   171,
   176,   179,   129,   188,   216,    16,    58,   105,    59,    60,
    61,   189,    62,    63,    64,    65,   190,   196,   186,    78,
   201,   206,   208,   198,   214,   215,   210,   211,   219,   220,
    66,    67,    68,    35,    36,    69,    39,   112,    78,    42,
    70,    71,    72,    73,    41,    52,    53,    74,    75,    76,
   145,    16,    58,     0,    59,    60,    61,     0,     0,    63,
    64,    65,     6,   153,     7,     0,     8,     9,    10,    11,
    12,    13,     0,     0,     0,     0,    66,    67,    68,    35,
   100,    69,     0,     0,    42,     0,    70,    71,    72,    73,
     0,    52,    53,    74,    75,    76,    16,    58,     0,    59,
    60,    61,     0,     0,    63,    64,    65,     6,     0,    51,
     0,     8,     9,    10,    11,    12,    13,     0,     0,     0,
     0,    66,    67,    68,    35,   203,    69,     0,     0,    42,
     0,    70,    71,    72,    73,     0,    52,    53,    74,    75,
    76,    16,    58,     0,    59,    60,    61,     0,     0,    63,
    64,    65,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,    16,     0,    66,    67,    68,    35,
   217,    69,    63,    64,    65,     0,    70,    71,    72,    73,
     0,    52,    53,    74,    75,    76,     0,    16,     0,    66,
    67,    68,     0,     0,    69,    63,    64,    65,     0,    70,
    71,    72,    73,     0,    52,    53,    74,    75,    76,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
   181,     0,    70,    71,    72,    73,     0,    52,    53,    74,
    75,    76,   120,   121,   122,   123,   199,     0,   124,   125,
   126,   127,   128,   129,   130,   131,   132,     0,   120,   121,
   122,   123,     0,     0,   124,   125,   126,   127,   128,   129,
   130,   131,   132,   120,   121,   122,   123,     0,     0,   124,
   125,   126,   127,   128,   129,   130,   131,   132,     0,     0,
     0,   120,   121,   122,   123,     0,   169,   124,   125,   126,
   127,   128,   129,   130,   131,   132,     0,     0,     0,   120,
   121,   122,   123,     0,   182,   124,   125,   126,   127,   128,
   129,   130,   131,   132,     0,     0,     0,   120,   121,   122,
   123,     0,   193,   124,   125,   126,   127,   128,   129,   130,
   131,   132,     0,     0,     0,   120,   121,   122,   123,     0,
   194,   124,   125,   126,   127,   128,   129,   130,   131,   132,
     0,   120,   121,   122,   123,     0,   185,   124,   125,   126,
   127,   128,   129,   130,   131,   132,   120,   121,   122,   123,
     0,   149,   124,   125,   126,   127,   128,   129,   130,   131,
   132,   120,   121,   122,   123,     0,   174,   124,   125,   126,
   127,   128,   129,   130,   131,   132,   120,   121,   122,   123,
     0,   175,   124,   125,   126,   127,   128,   129,   130,   131,
   132,   120,   121,   122,   123,     0,   200,   124,   125,   126,
   127,   128,   129,   130,   131,   132
};

static const short yycheck[] = {     7,
    41,    45,   140,     0,    15,    15,    14,     1,     3,    66,
    67,    68,    69,    15,   174,    23,     5,     0,     3,    30,
    31,    46,    47,    55,    56,    33,    70,    14,    37,    30,
    15,    16,    21,    18,    19,    20,   196,    45,    47,    36,
    37,    49,    50,    51,   101,    55,    56,   185,    42,    57,
   107,   108,    46,    36,    37,    57,    58,    59,    43,    14,
    61,    48,    70,   120,   121,   122,   123,   124,   125,   126,
   127,   128,   129,   130,   131,   132,   133,     7,   135,    26,
    27,    45,   139,    20,    21,    15,    30,    31,    45,    36,
    37,    15,    47,    40,    45,   103,   104,    34,    15,    26,
    27,   109,    36,    37,    46,    46,    23,    24,    25,    47,
    37,     4,    43,   170,   171,     8,     9,    10,    11,    12,
    13,   178,   179,    40,    41,    42,    46,    14,    45,    46,
    43,     3,   140,    50,    51,    52,    53,   145,    55,    56,
    57,    58,    59,    48,    45,    37,    45,   188,    26,    27,
    45,    45,    48,    44,    14,    18,    14,   201,    36,    37,
    38,    39,    40,     3,    47,    50,   174,    48,    50,    48,
    37,    45,    37,    43,   215,    15,    16,   185,    18,    19,
    20,    57,    22,    23,    24,    25,    37,    17,   196,   197,
    37,   199,    14,    57,    46,    43,   204,   205,     0,     0,
    40,    41,    42,    43,    29,    45,    33,    62,   216,     3,
    50,    51,    52,    53,    35,    55,    56,    57,    58,    59,
   109,    15,    16,    -1,    18,    19,    20,    -1,    -1,    23,
    24,    25,     4,   119,     6,    -1,     8,     9,    10,    11,
    12,    13,    -1,    -1,    -1,    -1,    40,    41,    42,    43,
    44,    45,    -1,    -1,     3,    -1,    50,    51,    52,    53,
    -1,    55,    56,    57,    58,    59,    15,    16,    -1,    18,
    19,    20,    -1,    -1,    23,    24,    25,     4,    -1,     6,
    -1,     8,     9,    10,    11,    12,    13,    -1,    -1,    -1,
    -1,    40,    41,    42,    43,    44,    45,    -1,    -1,     3,
    -1,    50,    51,    52,    53,    -1,    55,    56,    57,    58,
    59,    15,    16,    -1,    18,    19,    20,    -1,    -1,    23,
    24,    25,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    15,    -1,    40,    41,    42,    43,
    44,    45,    23,    24,    25,    -1,    50,    51,    52,    53,
    -1,    55,    56,    57,    58,    59,    -1,    15,    -1,    40,
    41,    42,    -1,    -1,    45,    23,    24,    25,    -1,    50,
    51,    52,    53,    -1,    55,    56,    57,    58,    59,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    14,    -1,    50,    51,    52,    53,    -1,    55,    56,    57,
    58,    59,    26,    27,    28,    29,    14,    -1,    32,    33,
    34,    35,    36,    37,    38,    39,    40,    -1,    26,    27,
    28,    29,    -1,    -1,    32,    33,    34,    35,    36,    37,
    38,    39,    40,    26,    27,    28,    29,    -1,    -1,    32,
    33,    34,    35,    36,    37,    38,    39,    40,    -1,    -1,
    -1,    26,    27,    28,    29,    -1,    49,    32,    33,    34,
    35,    36,    37,    38,    39,    40,    -1,    -1,    -1,    26,
    27,    28,    29,    -1,    49,    32,    33,    34,    35,    36,
    37,    38,    39,    40,    -1,    -1,    -1,    26,    27,    28,
    29,    -1,    49,    32,    33,    34,    35,    36,    37,    38,
    39,    40,    -1,    -1,    -1,    26,    27,    28,    29,    -1,
    49,    32,    33,    34,    35,    36,    37,    38,    39,    40,
    -1,    26,    27,    28,    29,    -1,    47,    32,    33,    34,
    35,    36,    37,    38,    39,    40,    26,    27,    28,    29,
    -1,    46,    32,    33,    34,    35,    36,    37,    38,    39,
    40,    26,    27,    28,    29,    -1,    46,    32,    33,    34,
    35,    36,    37,    38,    39,    40,    26,    27,    28,    29,
    -1,    46,    32,    33,    34,    35,    36,    37,    38,    39,
    40,    26,    27,    28,    29,    -1,    46,    32,    33,    34,
    35,    36,    37,    38,    39,    40
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 25 "my_YACC.y"
{printf("finished code!!!!!!!\n");;
    break;}
case 2:
#line 26 "my_YACC.y"
{printf("finished program: code MAIN\n");;
    break;}
case 4:
#line 30 "my_YACC.y"
{printf("code comments function\n");;
    break;}
case 5:
#line 31 "my_YACC.y"
{printf("code comments void_function\n");;
    break;}
case 12:
#line 52 "my_YACC.y"
{printf("args:ID COMMA args\n");;
    break;}
case 13:
#line 53 "my_YACC.y"
{printf("args:ID\n");;
    break;}
case 16:
#line 58 "my_YACC.y"
{;
    break;}
case 17:
#line 60 "my_YACC.y"
{printf("exp:exp BIGGER exp\n");;
    break;}
case 18:
#line 61 "my_YACC.y"
{printf("exp:exp BIGGER_EQ exp\n");;
    break;}
case 19:
#line 62 "my_YACC.y"
{printf("exp:exp SMALLER exp\n");;
    break;}
case 20:
#line 63 "my_YACC.y"
{printf("exp:exp SMALLER_EQ exp\n");;
    break;}
case 21:
#line 64 "my_YACC.y"
{printf("exp:exp EQUALIVATION exp\n");;
    break;}
case 22:
#line 65 "my_YACC.y"
{printf("exp:exp EQUAL exp\n");;
    break;}
case 23:
#line 66 "my_YACC.y"
{printf("exp:exp NOTEQUAL exp\n");;
    break;}
case 24:
#line 67 "my_YACC.y"
{printf("exp:exp PLUS exp\n");;
    break;}
case 25:
#line 68 "my_YACC.y"
{printf("exp:exp MINUS exp\n");;
    break;}
case 26:
#line 69 "my_YACC.y"
{printf("exp:exp MULTIPLY exp\n");;
    break;}
case 27:
#line 70 "my_YACC.y"
{printf("exp:exp DIVIDED exp\n");;
    break;}
case 28:
#line 71 "my_YACC.y"
{printf("exp:exp AND exp\n");;
    break;}
case 29:
#line 72 "my_YACC.y"
{printf("exp:exp OR exp\n");;
    break;}
case 30:
#line 73 "my_YACC.y"
{printf("exp:NOT exp\n");;
    break;}
case 31:
#line 74 "my_YACC.y"
{printf("exp:LP exp RP\n");;
    break;}
case 32:
#line 75 "my_YACC.y"
{printf("exp: literal \n");;
    break;}
case 33:
#line 76 "my_YACC.y"
{printf("exp: pointer_id \n");;
    break;}
case 34:
#line 77 "my_YACC.y"
{printf("exp:ADDRESS_OF exp\n");;
    break;}
case 35:
#line 82 "my_YACC.y"
{printf("exp:MULTIPLY exp\n");;
    break;}
case 37:
#line 86 "my_YACC.y"
{printf("literal:id\n");;
    break;}
case 38:
#line 87 "my_YACC.y"
{printf("literal:bool\n");;
    break;}
case 39:
#line 88 "my_YACC.y"
{printf("literal:char\n");;
    break;}
case 40:
#line 89 "my_YACC.y"
{printf("literal:STRING\n");;
    break;}
case 41:
#line 90 "my_YACC.y"
{printf("literal:NULL\n");;
    break;}
case 48:
#line 104 "my_YACC.y"
{printf("bool:TRUE\n");;
    break;}
case 49:
#line 106 "my_YACC.y"
{printf("bool:FALSE\n");;
    break;}
case 50:
#line 108 "my_YACC.y"
{printf("char:CHAR_uppercase\n");;
    break;}
case 51:
#line 109 "my_YACC.y"
{printf("char:CHAR_lowercase\n");;
    break;}
case 52:
#line 110 "my_YACC.y"
{printf("char:CHAR\n");;
    break;}
case 53:
#line 113 "my_YACC.y"
{printf("number:DEC_INT\n");;
    break;}
case 54:
#line 114 "my_YACC.y"
{printf("number:HEX_INT\n");;
    break;}
case 57:
#line 120 "my_YACC.y"
{printf("var_dec:var_dec premitive_dec\n");;
    break;}
case 58:
#line 121 "my_YACC.y"
{printf("var_dec:var_dec string_dec\n");;
    break;}
case 59:
#line 122 "my_YACC.y"
{printf("var_dec: epsilon\n");;
    break;}
case 60:
#line 124 "my_YACC.y"
{printf("premitive_dec:VAR type premitive_assign_op EOS");;
    break;}
case 61:
#line 127 "my_YACC.y"
{printf("string_dec:TYPE_STRING string_assign_op EOS\n");;
    break;}
case 62:
#line 129 "my_YACC.y"
{printf("string_assign_op:ID BSI exp ESI \n");;
    break;}
case 63:
#line 130 "my_YACC.y"
{printf("string_assign_op:ID BSI exp ESI COMMA string_assign_op \n");;
    break;}
case 64:
#line 131 "my_YACC.y"
{printf("string_assign_op:ID BSI exp ESI EQUAL string \n");;
    break;}
case 65:
#line 132 "my_YACC.y"
{printf("string_assign_op:ID BSI exp ESI EQUAL string COMMA string_assign_op \n");;
    break;}
case 66:
#line 135 "my_YACC.y"
{printf("premitive_assign_op:ID\n");;
    break;}
case 67:
#line 136 "my_YACC.y"
{printf("premitive_assign_op:ID COMMApremitive_assign_op \n");;
    break;}
case 68:
#line 137 "my_YACC.y"
{printf("premitive_assign_op:ID EQUAL exp \n");;
    break;}
case 69:
#line 138 "my_YACC.y"
{printf("premitive_assign_op:ID EQUAL exp COMMA premitive_assign_op \n");;
    break;}
case 70:
#line 141 "my_YACC.y"
{printf("string:STRING\n");;
    break;}
case 71:
#line 142 "my_YACC.y"
{printf("string:EMPTY_STRING\n");;
    break;}
case 72:
#line 148 "my_YACC.y"
{printf("(TYPE__INT)\n");;
    break;}
case 73:
#line 149 "my_YACC.y"
{printf("(TYPE__CHAR)\n");
    break;}
case 74:
#line 150 "my_YACC.y"
{printf("(TYPE__REAL)\n");;
    break;}
case 75:
#line 151 "my_YACC.y"
{printf("(TYPE__BOOL)\n");;
    break;}
case 76:
#line 152 "my_YACC.y"
{printf("(TYPE__INT*)\n");;
    break;}
case 77:
#line 153 "my_YACC.y"
{printf("(TYPE__char*)\n");;
    break;}
case 78:
#line 154 "my_YACC.y"
{printf("(TYPE__REAL*)\n");;
    break;}
case 81:
#line 166 "my_YACC.y"
{printf("block:SCB body ECB\n");;
    break;}
case 83:
#line 168 "my_YACC.y"
{printf("block:SCB body ECB\n");;
    break;}
case 84:
#line 170 "my_YACC.y"
{printf("body_:ifelse\n");
    break;}
case 85:
#line 171 "my_YACC.y"
{printf("body_:loop\n");
    break;}
case 86:
#line 172 "my_YACC.y"
{printf("body_:function\n");
    break;}
case 87:
#line 173 "my_YACC.y"
{printf("body_:void_function\n");
    break;}
case 88:
#line 174 "my_YACC.y"
{printf("body_:function_call\n");
    break;}
case 90:
#line 182 "my_YACC.y"
{printf("function_call:ID LP RP \n");;
    break;}
case 91:
#line 183 "my_YACC.y"
{printf("function_call:ID LP exp_list RP \n");;
    break;}
case 92:
#line 185 "my_YACC.y"
{printf("exp_list:exp\n");;
    break;}
case 93:
#line 186 "my_YACC.y"
{printf("exp_list:exp_list COMMA exp\n");;
    break;}
case 94:
#line 189 "my_YACC.y"
{printf("if:IF LP exp RP SCB body ECB \n");;
    break;}
case 96:
#line 194 "my_YACC.y"
{printf("i'm while loop\n");;
    break;}
case 97:
#line 195 "my_YACC.y"
{printf("loop: for_loop\n");;
    break;}
case 98:
#line 196 "my_YACC.y"
{printf("loop:DO SCB body ECB WHILE LP exp RP EOS\n");;
    break;}
case 100:
#line 200 "my_YACC.y"
{printf("i++\n");;
    break;}
case 101:
#line 201 "my_YACC.y"
{printf("++i\n");;
    break;}
case 102:
#line 202 "my_YACC.y"
{printf("i--\n");;
    break;}
case 103:
#line 203 "my_YACC.y"
{printf("--i\n");;
    break;}
case 104:
#line 205 "my_YACC.y"
{printf("loop_i_dec: INT ID EQUAL DEC_INT\n");;
    break;}
case 105:
#line 206 "my_YACC.y"
{printf("loop_i_dec:ID EQUAL DEC_INT\n");;
    break;}
case 106:
#line 207 "my_YACC.y"
{printf("loop_i_dec: ID\n");;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 209 "my_YACC.y"


#include "lex.yy.c"
int main() {return yyparse();}

int yyerror(){
 	fflush(stdout);
 	fprintf(stderr, "\n\n------------------------------------------------------\nError located in line: %d\n", yylineno);
	fprintf(stderr, "The parser can not accept: \" %s \" .\n",yytext);
	return 0;
}


int yywrap(){
	return 1;
}
