#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from my_YACC.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "my_YACC.y"

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
extern int yylex();
extern int yylineno;

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"
#ifndef YY_USE_CLASS
# ifndef YYSTYPE
#  define YYSTYPE int
#  define YYSTYPE_IS_TRIVIAL 1
# endif
#endif

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	FUNCTION	258
#define	TYPE_BOOL	259
#define	TYPE_STRING	260
#define	TYPE_VOID	261
#define	MAIN	262
#define	TYPE_INT	263
#define	TYPE_CHAR	264
#define	TYPE_REAL	265
#define	TYPE_P_INT	266
#define	TYPE_P_CHAR	267
#define	TYPE_P_REAL	268
#define	COMMENTS	269
#define	ILLEGAL_COMMENT	270
#define	EOS	271
#define	ID	272
#define	IF	273
#define	ELSE	274
#define	WHILE	275
#define	FOR	276
#define	DO	277
#define	VAR	278
#define	RETURN	279
#define	TRUE	280
#define	FALSE	281
#define	NULL	282
#define	AND	283
#define	OR	284
#define	EQUALIVATION	285
#define	NOTEQUAL	286
#define	PLUSONE	287
#define	MINUSONE	288
#define	BIGGER_EQ	289
#define	SMALLER_EQ	290
#define	BIGGER	291
#define	SMALLER	292
#define	DIVIDED	293
#define	EQUAL	294
#define	PLUS	295
#define	MINUS	296
#define	MULTIPLY	297
#define	NOT	298
#define	ADDRESS_OF	299
#define	SCB	300
#define	ECB	301
#define	LP	302
#define	RP	303
#define	COMMA	304
#define	BSI	305
#define	ESI	306
#define	DLOS	307
#define	ILLEGAL_POINTER	308
#define	POINTER	309
#define	CHAR_lowercase	310
#define	CHAR_uppercase	311
#define	CHAR	312
#define	INT	313
#define	INVALID_STRING	314
#define	STRING	315
#define	EMPTY_STRING	316
#define	DEC_INT	317
#define	HEX_INT	318
#define	REAL	319


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int FUNCTION;
static const int TYPE_BOOL;
static const int TYPE_STRING;
static const int TYPE_VOID;
static const int MAIN;
static const int TYPE_INT;
static const int TYPE_CHAR;
static const int TYPE_REAL;
static const int TYPE_P_INT;
static const int TYPE_P_CHAR;
static const int TYPE_P_REAL;
static const int COMMENTS;
static const int ILLEGAL_COMMENT;
static const int EOS;
static const int ID;
static const int IF;
static const int ELSE;
static const int WHILE;
static const int FOR;
static const int DO;
static const int VAR;
static const int RETURN;
static const int TRUE;
static const int FALSE;
static const int NULL;
static const int AND;
static const int OR;
static const int EQUALIVATION;
static const int NOTEQUAL;
static const int PLUSONE;
static const int MINUSONE;
static const int BIGGER_EQ;
static const int SMALLER_EQ;
static const int BIGGER;
static const int SMALLER;
static const int DIVIDED;
static const int EQUAL;
static const int PLUS;
static const int MINUS;
static const int MULTIPLY;
static const int NOT;
static const int ADDRESS_OF;
static const int SCB;
static const int ECB;
static const int LP;
static const int RP;
static const int COMMA;
static const int BSI;
static const int ESI;
static const int DLOS;
static const int ILLEGAL_POINTER;
static const int POINTER;
static const int CHAR_lowercase;
static const int CHAR_uppercase;
static const int CHAR;
static const int INT;
static const int INVALID_STRING;
static const int STRING;
static const int EMPTY_STRING;
static const int DEC_INT;
static const int HEX_INT;
static const int REAL;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,FUNCTION=258
	,TYPE_BOOL=259
	,TYPE_STRING=260
	,TYPE_VOID=261
	,MAIN=262
	,TYPE_INT=263
	,TYPE_CHAR=264
	,TYPE_REAL=265
	,TYPE_P_INT=266
	,TYPE_P_CHAR=267
	,TYPE_P_REAL=268
	,COMMENTS=269
	,ILLEGAL_COMMENT=270
	,EOS=271
	,ID=272
	,IF=273
	,ELSE=274
	,WHILE=275
	,FOR=276
	,DO=277
	,VAR=278
	,RETURN=279
	,TRUE=280
	,FALSE=281
	,NULL=282
	,AND=283
	,OR=284
	,EQUALIVATION=285
	,NOTEQUAL=286
	,PLUSONE=287
	,MINUSONE=288
	,BIGGER_EQ=289
	,SMALLER_EQ=290
	,BIGGER=291
	,SMALLER=292
	,DIVIDED=293
	,EQUAL=294
	,PLUS=295
	,MINUS=296
	,MULTIPLY=297
	,NOT=298
	,ADDRESS_OF=299
	,SCB=300
	,ECB=301
	,LP=302
	,RP=303
	,COMMA=304
	,BSI=305
	,ESI=306
	,DLOS=307
	,ILLEGAL_POINTER=308
	,POINTER=309
	,CHAR_lowercase=310
	,CHAR_uppercase=311
	,CHAR=312
	,INT=313
	,INVALID_STRING=314
	,STRING=315
	,EMPTY_STRING=316
	,DEC_INT=317
	,HEX_INT=318
	,REAL=319


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::FUNCTION=258;
const int YY_parse_CLASS::TYPE_BOOL=259;
const int YY_parse_CLASS::TYPE_STRING=260;
const int YY_parse_CLASS::TYPE_VOID=261;
const int YY_parse_CLASS::MAIN=262;
const int YY_parse_CLASS::TYPE_INT=263;
const int YY_parse_CLASS::TYPE_CHAR=264;
const int YY_parse_CLASS::TYPE_REAL=265;
const int YY_parse_CLASS::TYPE_P_INT=266;
const int YY_parse_CLASS::TYPE_P_CHAR=267;
const int YY_parse_CLASS::TYPE_P_REAL=268;
const int YY_parse_CLASS::COMMENTS=269;
const int YY_parse_CLASS::ILLEGAL_COMMENT=270;
const int YY_parse_CLASS::EOS=271;
const int YY_parse_CLASS::ID=272;
const int YY_parse_CLASS::IF=273;
const int YY_parse_CLASS::ELSE=274;
const int YY_parse_CLASS::WHILE=275;
const int YY_parse_CLASS::FOR=276;
const int YY_parse_CLASS::DO=277;
const int YY_parse_CLASS::VAR=278;
const int YY_parse_CLASS::RETURN=279;
const int YY_parse_CLASS::TRUE=280;
const int YY_parse_CLASS::FALSE=281;
const int YY_parse_CLASS::NULL=282;
const int YY_parse_CLASS::AND=283;
const int YY_parse_CLASS::OR=284;
const int YY_parse_CLASS::EQUALIVATION=285;
const int YY_parse_CLASS::NOTEQUAL=286;
const int YY_parse_CLASS::PLUSONE=287;
const int YY_parse_CLASS::MINUSONE=288;
const int YY_parse_CLASS::BIGGER_EQ=289;
const int YY_parse_CLASS::SMALLER_EQ=290;
const int YY_parse_CLASS::BIGGER=291;
const int YY_parse_CLASS::SMALLER=292;
const int YY_parse_CLASS::DIVIDED=293;
const int YY_parse_CLASS::EQUAL=294;
const int YY_parse_CLASS::PLUS=295;
const int YY_parse_CLASS::MINUS=296;
const int YY_parse_CLASS::MULTIPLY=297;
const int YY_parse_CLASS::NOT=298;
const int YY_parse_CLASS::ADDRESS_OF=299;
const int YY_parse_CLASS::SCB=300;
const int YY_parse_CLASS::ECB=301;
const int YY_parse_CLASS::LP=302;
const int YY_parse_CLASS::RP=303;
const int YY_parse_CLASS::COMMA=304;
const int YY_parse_CLASS::BSI=305;
const int YY_parse_CLASS::ESI=306;
const int YY_parse_CLASS::DLOS=307;
const int YY_parse_CLASS::ILLEGAL_POINTER=308;
const int YY_parse_CLASS::POINTER=309;
const int YY_parse_CLASS::CHAR_lowercase=310;
const int YY_parse_CLASS::CHAR_uppercase=311;
const int YY_parse_CLASS::CHAR=312;
const int YY_parse_CLASS::INT=313;
const int YY_parse_CLASS::INVALID_STRING=314;
const int YY_parse_CLASS::STRING=315;
const int YY_parse_CLASS::EMPTY_STRING=316;
const int YY_parse_CLASS::DEC_INT=317;
const int YY_parse_CLASS::HEX_INT=318;
const int YY_parse_CLASS::REAL=319;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		207
#define	YYFLAG		-32768
#define	YYNTBASE	65

#define YYTRANSLATE(x) ((unsigned)(x) <= 319 ? yytranslate[x] : 100)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45,
    46,    47,    48,    49,    50,    51,    52,    53,    54,    55,
    56,    57,    58,    59,    60,    61,    62,    63,    64
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     4,    14,    16,    18,    20,    22,    23,    25,
    26,    36,    39,    42,    44,    55,    60,    64,    66,    71,
    72,    76,    80,    84,    88,    92,    96,   100,   104,   108,
   112,   116,   120,   123,   127,   129,   131,   134,   137,   139,
   141,   143,   145,   147,   149,   151,   153,   155,   157,   159,
   161,   163,   165,   167,   169,   171,   173,   175,   178,   181,
   182,   187,   191,   196,   203,   210,   219,   221,   225,   229,
   235,   237,   239,   242,   243,   244,   246,   248,   250,   252,
   254,   256,   258,   260,   263,   267,   269,   271,   276,   278,
   280,   282,   284,   286,   288,   289,   293,   298,   300,   304,
   312,   324,   332,   334,   342,   354,   357,   360,   363,   366,
   371,   375
};

static const short yyrhs[] = {    67,
     0,    66,     0,     3,     6,     7,    47,    74,    48,    45,
    72,    46,     0,    67,     0,    71,     0,    69,     0,    68,
     0,     0,    14,     0,     0,     3,     6,    70,    47,    74,
    48,    45,    72,    46,     0,    68,    69,     0,    69,    68,
     0,    17,     0,     3,    89,    70,    47,    74,    48,    45,
    90,    91,    46,     0,    45,    82,    88,    46,     0,    70,
    49,    73,     0,    70,     0,    89,    73,    16,    74,     0,
     0,    75,    36,    75,     0,    75,    34,    75,     0,    75,
    37,    75,     0,    75,    35,    75,     0,    75,    30,    75,
     0,    75,    31,    75,     0,    75,    40,    75,     0,    75,
    41,    75,     0,    75,    42,    75,     0,    75,    38,    75,
     0,    75,    28,    75,     0,    75,    29,    75,     0,    43,
    75,     0,    47,    75,    48,     0,    77,     0,    76,     0,
    44,    75,     0,    42,    75,     0,    70,     0,    78,     0,
    79,     0,    80,     0,    81,     0,    60,     0,    61,     0,
    27,     0,    62,     0,    63,     0,    64,     0,    25,     0,
    26,     0,    56,     0,    55,     0,    57,     0,    62,     0,
    63,     0,    64,     0,    82,    83,     0,    82,    84,     0,
     0,    23,    89,    86,    16,     0,     5,    85,    16,     0,
    70,    50,    75,    51,     0,    70,    50,    75,    51,    49,
    85,     0,    70,    50,    75,    51,    39,    87,     0,    70,
    50,    75,    51,    39,    87,    49,    85,     0,    70,     0,
    70,    49,    86,     0,    70,    39,    75,     0,    70,    39,
    75,    49,    86,     0,    60,     0,    61,     0,    88,    92,
     0,     0,     0,     8,     0,     9,     0,    10,     0,     4,
     0,    11,     0,    12,     0,    13,     0,    88,     0,    24,
    77,     0,     0,    39,    75,     0,    70,     0,    76,     0,
    70,    50,    75,    51,     0,    95,     0,    96,     0,    71,
     0,    69,     0,    93,     0,    72,     0,     0,    70,    47,
    48,     0,    70,    47,    94,    48,     0,    75,     0,    94,
    49,    75,     0,    18,    47,    75,    48,    45,    88,    46,
     0,    18,    47,    75,    48,    45,    88,    46,    19,    45,
    88,    46,     0,    20,    47,    75,    48,    45,    88,    46,
     0,    97,     0,    22,    72,    20,    47,    75,    48,    16,
     0,    21,    47,    99,    16,    75,    16,    98,    48,    45,
    88,    46,     0,    70,    32,     0,    32,    70,     0,    70,
    33,     0,    33,    70,     0,    58,    70,    39,    62,     0,
    70,    39,    62,     0,    70,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    25,    26,    28,    30,    31,    32,    33,    34,    36,    37,
    39,    40,    41,    44,    46,    48,    50,    51,    55,    56,
    58,    59,    60,    61,    62,    63,    64,    65,    66,    67,
    68,    69,    70,    71,    73,    74,    75,    80,    83,    84,
    86,    87,    88,    89,    90,    91,    93,    94,    96,    98,
    99,   101,   102,   103,   106,   107,   108,   111,   112,   113,
   115,   118,   120,   121,   122,   123,   126,   127,   128,   129,
   132,   133,   137,   138,   140,   142,   143,   144,   145,   146,
   147,   148,   150,   154,   156,   158,   159,   160,   163,   164,
   165,   166,   167,   168,   169,   171,   172,   174,   175,   178,
   179,   183,   184,   185,   187,   189,   190,   191,   192,   194,
   195,   196
};

static const char * const yytname[] = {   "$","error","$illegal.","FUNCTION",
"TYPE_BOOL","TYPE_STRING","TYPE_VOID","MAIN","TYPE_INT","TYPE_CHAR","TYPE_REAL",
"TYPE_P_INT","TYPE_P_CHAR","TYPE_P_REAL","COMMENTS","ILLEGAL_COMMENT","EOS",
"ID","IF","ELSE","WHILE","FOR","DO","VAR","RETURN","TRUE","FALSE","NULL","AND",
"OR","EQUALIVATION","NOTEQUAL","PLUSONE","MINUSONE","BIGGER_EQ","SMALLER_EQ",
"BIGGER","SMALLER","DIVIDED","EQUAL","PLUS","MINUS","MULTIPLY","NOT","ADDRESS_OF",
"SCB","ECB","LP","RP","COMMA","BSI","ESI","DLOS","ILLEGAL_POINTER","POINTER",
"CHAR_lowercase","CHAR_uppercase","CHAR","INT","INVALID_STRING","STRING","EMPTY_STRING",
"DEC_INT","HEX_INT","REAL","main_program","main_func","code","comments","void_function",
"id","function","code_block","args","parameter_list","exp","pointer_id","literal",
"int","real","bool","char","var_dec","premitive_dec","string_dec","string_assign_op",
"premitive_assign_op","string","body","type","func_body","return","body_","function_call",
"exp_list","ifelse","loop","for_loop","inc_dec","loop_i_dec","loop"
};
#endif

static const short yyr1[] = {     0,
    65,    65,    66,    67,    67,    67,    67,    67,    68,    68,
    69,    69,    69,    70,    71,    72,    73,    73,    74,    74,
    75,    75,    75,    75,    75,    75,    75,    75,    75,    75,
    75,    75,    75,    75,    75,    75,    75,    76,    77,    77,
    77,    77,    77,    77,    77,    77,    78,    78,    79,    80,
    80,    81,    81,    81,    -1,    -1,    -1,    82,    82,    82,
    83,    84,    85,    85,    85,    85,    86,    86,    86,    86,
    87,    87,    88,    88,    -1,    89,    89,    89,    89,    89,
    89,    89,    90,    91,    -1,    -1,    -1,    -1,    92,    92,
    92,    92,    92,    92,    92,    93,    93,    94,    94,    95,
    95,    96,    96,    96,    97,    98,    98,    98,    98,    99,
    99,    99
};

static const short yyr2[] = {     0,
     1,     1,     9,     1,     1,     1,     1,     0,     1,     0,
     9,     2,     2,     1,    10,     4,     3,     1,     4,     0,
     3,     3,     3,     3,     3,     3,     3,     3,     3,     3,
     3,     3,     2,     3,     1,     1,     2,     2,     1,     1,
     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
     1,     1,     1,     1,     1,     1,     1,     2,     2,     0,
     4,     3,     4,     6,     6,     8,     1,     3,     3,     5,
     1,     1,     2,     0,     0,     1,     1,     1,     1,     1,
     1,     1,     1,     2,     3,     1,     1,     4,     1,     1,
     1,     1,     1,     1,     0,     3,     4,     1,     3,     7,
    11,     7,     1,     7,    11,     2,     2,     2,     2,     4,
     3,     1
};

static const short yydefact[] = {     8,
     0,     9,     2,     1,     7,     6,     5,    79,     0,    76,
    77,    78,    80,    81,    82,     0,     0,     0,    10,    13,
     0,    14,     0,     0,     0,    20,    20,    20,     0,     0,
     0,     0,     0,    18,     0,     0,     0,     0,     0,    20,
     0,    74,    60,     0,    17,    19,     0,    83,     0,    74,
     3,    11,     0,     0,     0,     0,     0,    10,     0,    91,
    94,    73,    93,    89,    90,   103,     0,     0,     0,     0,
    58,    59,     0,     0,     0,     0,     0,     0,    50,    51,
    46,    53,    52,    54,    44,    45,    47,    48,    49,    39,
    84,    40,    41,    42,    43,    15,     0,     0,     0,    16,
     0,     0,     0,     0,     0,    36,    35,     0,     0,   112,
     0,     0,    96,    98,     0,     0,    62,    67,     0,    38,
    33,    37,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,    97,     0,     0,     0,     0,    61,    34,    31,    32,
    25,    26,    22,    24,    21,    23,    30,    27,    28,    29,
    74,    74,     0,   111,     0,     0,    99,    63,    69,    68,
     0,     0,   110,     0,     0,     0,     0,     0,   100,   102,
     0,     0,     0,     0,   104,    71,    72,    65,    64,    70,
     0,   107,   109,   106,   108,     0,     0,    74,    74,    66,
     0,     0,   101,   105,     0,     0,     0
};

static const short yydefgoto[] = {   205,
     3,     4,    18,    58,    90,    60,    61,    35,    29,   105,
   106,   107,    92,    93,    94,    95,    50,    71,    72,    98,
   119,   188,    48,    30,    49,    68,    62,    63,   115,    64,
    65,    66,   184,   111
};

static const short yypact[] = {    20,
   286,-32768,-32768,-32768,    29,     6,-32768,-32768,    56,-32768,
-32768,-32768,-32768,-32768,-32768,    -2,    21,    29,     6,-32768,
   -23,-32768,   -18,    -3,    -2,   144,   144,   144,   -10,    -2,
    17,    26,    23,    27,    90,    65,    66,    79,    -2,   144,
    79,-32768,-32768,    73,-32768,-32768,    77,   265,   104,    14,
-32768,-32768,   425,    25,    85,    96,    79,     6,    97,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,   -15,    99,    -2,   144,
-32768,-32768,   196,   134,   134,     1,   116,    78,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,   108,   130,    -2,-32768,
   134,   134,   134,   134,   326,-32768,-32768,   341,    -2,   125,
   131,   119,-32768,   386,    22,   134,-32768,    50,   151,    63,
-32768,-32768,   356,   134,   134,   134,   134,   134,   134,   134,
   134,   134,   134,   134,   134,   126,   129,   136,   117,   134,
   134,-32768,   134,   292,   134,    -2,-32768,-32768,-32768,-32768,
    89,    89,    89,    89,    89,    89,    63,    24,    24,    63,
-32768,-32768,   118,-32768,   277,   371,   386,    58,   310,-32768,
   205,   217,-32768,    18,   154,    48,    -2,    -2,   163,-32768,
    -2,    -2,    83,   135,-32768,-32768,-32768,   137,-32768,-32768,
   139,-32768,-32768,-32768,-32768,   140,    -2,-32768,-32768,-32768,
   226,   256,-32768,-32768,   187,   200,-32768
};

static const short yypgoto[] = {-32768,
-32768,-32768,     3,     8,    -9,   201,   -24,   164,    74,   -47,
-32768,   138,-32768,-32768,-32768,-32768,-32768,-32768,-32768,  -172,
  -142,-32768,   -49,     5,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768
};


#define	YYLAST		438


static const short yytable[] = {    23,
    73,    22,     5,   170,   189,    16,    24,     6,    20,    79,
    80,    81,    19,    44,    22,    23,    47,    22,    69,     2,
    34,    20,     1,    26,   200,    19,    25,   108,    27,    34,
   114,    17,    77,     2,    22,   190,    70,    33,    59,    82,
    83,    84,     2,    28,    85,    86,    87,    88,    89,   181,
   182,   124,   125,   120,   121,   122,   123,    16,   109,    97,
    20,   132,    21,    59,    36,   135,   110,    38,   144,   142,
   143,    74,    22,    37,    99,    39,   149,   150,   151,   152,
   153,   154,   155,   156,   157,   158,   159,   160,   145,   118,
   124,   125,   165,   166,    22,   167,   176,   169,   146,   138,
    31,    32,    79,    80,    81,    40,   177,   186,   187,    41,
    42,   171,   172,    46,   194,   195,   124,   125,    51,   101,
   102,   103,    52,    43,   104,   113,   132,    67,   133,   134,
   135,    75,    82,    83,    84,   112,   118,    85,    86,    87,
    88,    89,    76,    78,    96,   117,   140,     8,   201,   202,
    22,    10,    11,    12,    13,    14,    15,   116,    79,    80,
    81,    59,    59,   139,   183,   141,   147,    97,   118,   185,
   161,   192,   193,   162,   163,   101,   102,   103,   164,   173,
   104,   191,   196,   198,   199,   197,   206,    97,    82,    83,
    84,    59,    59,    85,    86,    87,    88,    89,    53,   207,
     7,     0,    45,     0,    91,     0,     0,    53,     0,     2,
     0,     0,    22,    54,     0,    55,    56,    57,     2,    53,
     0,    22,    54,     0,    55,    56,    57,     0,    53,     0,
     2,     0,     0,    22,    54,     0,    55,    56,    57,     2,
    43,   100,    22,    54,     0,    55,    56,    57,     0,    43,
   179,     0,     0,     0,     0,     0,     0,     0,    53,     0,
     0,    43,   180,     0,     0,     0,     0,    53,     0,     2,
    43,   203,    22,    54,     0,    55,    56,    57,     2,     0,
     0,    22,    54,     0,    55,    56,    57,     0,     0,     8,
     0,     9,   174,    10,    11,    12,    13,    14,    15,     0,
    43,   204,     0,     0,   124,   125,   126,   127,     0,    43,
   128,   129,   130,   131,   132,     0,   133,   134,   135,   124,
   125,   126,   127,     0,     0,   128,   129,   130,   131,   132,
     0,   133,   134,   135,     0,     0,     0,   124,   125,   126,
   127,     0,   168,   128,   129,   130,   131,   132,     0,   133,
   134,   135,     0,   124,   125,   126,   127,     0,   178,   128,
   129,   130,   131,   132,     0,   133,   134,   135,   124,   125,
   126,   127,     0,   136,   128,   129,   130,   131,   132,     0,
   133,   134,   135,   124,   125,   126,   127,     0,   137,   128,
   129,   130,   131,   132,     0,   133,   134,   135,   124,   125,
   126,   127,     0,   148,   128,   129,   130,   131,   132,     0,
   133,   134,   135,   124,   125,   126,   127,     0,   175,   128,
   129,   130,   131,   132,     0,   133,   134,   135,     8,     0,
    25,     0,    10,    11,    12,    13,    14,    15
};

static const short yycheck[] = {     9,
    50,    17,     0,   146,   177,     1,    16,     0,     6,    25,
    26,    27,     5,    38,    17,    25,    41,    17,     5,    14,
    30,    19,     3,    47,   197,    18,     6,    75,    47,    39,
    78,     3,    57,    14,    17,   178,    23,    48,    48,    55,
    56,    57,    14,    47,    60,    61,    62,    63,    64,    32,
    33,    28,    29,   101,   102,   103,   104,    53,    58,    69,
    58,    38,     7,    73,    48,    42,    76,    45,   116,    48,
    49,    47,    17,    48,    70,    49,   124,   125,   126,   127,
   128,   129,   130,   131,   132,   133,   134,   135,    39,    99,
    28,    29,   140,   141,    17,   143,    39,   145,    49,   109,
    27,    28,    25,    26,    27,    16,    49,    60,    61,    45,
    45,   161,   162,    40,    32,    33,    28,    29,    46,    42,
    43,    44,    46,    45,    47,    48,    38,    24,    40,    41,
    42,    47,    55,    56,    57,    20,   146,    60,    61,    62,
    63,    64,    47,    47,    46,    16,    16,     4,   198,   199,
    17,     8,     9,    10,    11,    12,    13,    50,    25,    26,
    27,   171,   172,    39,   174,    47,    16,   177,   178,    16,
    45,   181,   182,    45,    39,    42,    43,    44,    62,    62,
    47,    19,    48,    45,    45,    49,     0,   197,    55,    56,
    57,   201,   202,    60,    61,    62,    63,    64,     3,     0,
     0,    -1,    39,    -1,    67,    -1,    -1,     3,    -1,    14,
    -1,    -1,    17,    18,    -1,    20,    21,    22,    14,     3,
    -1,    17,    18,    -1,    20,    21,    22,    -1,     3,    -1,
    14,    -1,    -1,    17,    18,    -1,    20,    21,    22,    14,
    45,    46,    17,    18,    -1,    20,    21,    22,    -1,    45,
    46,    -1,    -1,    -1,    -1,    -1,    -1,    -1,     3,    -1,
    -1,    45,    46,    -1,    -1,    -1,    -1,     3,    -1,    14,
    45,    46,    17,    18,    -1,    20,    21,    22,    14,    -1,
    -1,    17,    18,    -1,    20,    21,    22,    -1,    -1,     4,
    -1,     6,    16,     8,     9,    10,    11,    12,    13,    -1,
    45,    46,    -1,    -1,    28,    29,    30,    31,    -1,    45,
    34,    35,    36,    37,    38,    -1,    40,    41,    42,    28,
    29,    30,    31,    -1,    -1,    34,    35,    36,    37,    38,
    -1,    40,    41,    42,    -1,    -1,    -1,    28,    29,    30,
    31,    -1,    51,    34,    35,    36,    37,    38,    -1,    40,
    41,    42,    -1,    28,    29,    30,    31,    -1,    49,    34,
    35,    36,    37,    38,    -1,    40,    41,    42,    28,    29,
    30,    31,    -1,    48,    34,    35,    36,    37,    38,    -1,
    40,    41,    42,    28,    29,    30,    31,    -1,    48,    34,
    35,    36,    37,    38,    -1,    40,    41,    42,    28,    29,
    30,    31,    -1,    48,    34,    35,    36,    37,    38,    -1,
    40,    41,    42,    28,    29,    30,    31,    -1,    48,    34,
    35,    36,    37,    38,    -1,    40,    41,    42,     4,    -1,
     6,    -1,     8,     9,    10,    11,    12,    13
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 2:
#line 26 "my_YACC.y"
{printf("program: code MAIN\n");;
    break;}
case 5:
#line 31 "my_YACC.y"
{printf("code commenst function\n");;
    break;}
case 6:
#line 32 "my_YACC.y"
{printf("code commenst void_function\n");;
    break;}
case 16:
#line 48 "my_YACC.y"
{printf("block:SCB body ECB");;
    break;}
case 17:
#line 50 "my_YACC.y"
{printf("args:ID COMMA args\n");;
    break;}
case 18:
#line 51 "my_YACC.y"
{printf("args:ID\n");;
    break;}
case 21:
#line 58 "my_YACC.y"
{printf("exp:exp BIGGER exp\n");;
    break;}
case 22:
#line 59 "my_YACC.y"
{printf("exp:exp BIGGER_EQ exp\n");;
    break;}
case 23:
#line 60 "my_YACC.y"
{printf("exp:exp SMALLER exp\n");;
    break;}
case 24:
#line 61 "my_YACC.y"
{printf("exp:exp SMALLER_EQ exp\n");;
    break;}
case 25:
#line 62 "my_YACC.y"
{printf("exp:exp EQUALIVATION exp\n");;
    break;}
case 26:
#line 63 "my_YACC.y"
{printf("exp:exp NOTEQUAL exp\n");;
    break;}
case 27:
#line 64 "my_YACC.y"
{printf("exp:exp PLUS exp\n");;
    break;}
case 28:
#line 65 "my_YACC.y"
{printf("exp:exp MINUS exp\n");;
    break;}
case 29:
#line 66 "my_YACC.y"
{printf("exp:exp MULTIPLY exp\n");;
    break;}
case 30:
#line 67 "my_YACC.y"
{printf("exp:exp DIVIDED exp\n");;
    break;}
case 31:
#line 68 "my_YACC.y"
{printf("exp:exp AND exp\n");;
    break;}
case 32:
#line 69 "my_YACC.y"
{printf("exp:exp OR exp\n");;
    break;}
case 33:
#line 70 "my_YACC.y"
{printf("exp:NOT exp\n");;
    break;}
case 34:
#line 71 "my_YACC.y"
{printf("exp:LP exp RP\n");;
    break;}
case 35:
#line 73 "my_YACC.y"
{printf("exp: literal \n");;
    break;}
case 37:
#line 75 "my_YACC.y"
{printf("exp:ADDRESS_OF exp\n");;
    break;}
case 38:
#line 80 "my_YACC.y"
{printf("exp:MULTIPLY exp\n");;
    break;}
case 39:
#line 83 "my_YACC.y"
{printf("literal:id\n");;
    break;}
case 40:
#line 84 "my_YACC.y"
{printf("literal:DEC_INT\n");;
    break;}
case 41:
#line 86 "my_YACC.y"
{printf("literal:REAL\n");;
    break;}
case 42:
#line 87 "my_YACC.y"
{printf("literal:bool\n");;
    break;}
case 43:
#line 88 "my_YACC.y"
{printf("literal:char\n");;
    break;}
case 44:
#line 89 "my_YACC.y"
{printf("literal:STRING\n");;
    break;}
case 45:
#line 90 "my_YACC.y"
{printf("literal:EMPTY_STRING\n");;
    break;}
case 46:
#line 91 "my_YACC.y"
{printf("literal:NULL\n");;
    break;}
case 50:
#line 98 "my_YACC.y"
{printf("bool:TRUE\n");;
    break;}
case 51:
#line 99 "my_YACC.y"
{printf("bool:FALSE\n");;
    break;}
case 52:
#line 101 "my_YACC.y"
{printf("char:CHAR_uppercase\n");;
    break;}
case 53:
#line 102 "my_YACC.y"
{printf("char:CHAR_lowercase\n");;
    break;}
case 54:
#line 103 "my_YACC.y"
{printf("char:CHAR\n");;
    break;}
case 55:
#line 106 "my_YACC.y"
{printf("number:DEC_INT\n");;
    break;}
case 56:
#line 107 "my_YACC.y"
{printf("number:HEX_INT\n");;
    break;}
case 57:
#line 108 "my_YACC.y"
{printf("number:REAL\n");;
    break;}
case 58:
#line 111 "my_YACC.y"
{printf("var_dec:var_dec premitive_dec");;
    break;}
case 59:
#line 112 "my_YACC.y"
{printf("var_dec:var_dec string_dec");;
    break;}
case 61:
#line 115 "my_YACC.y"
{printf("premitive_dec:VAR type premitive_assign_op EOS");;
    break;}
case 62:
#line 118 "my_YACC.y"
{printf("string_dec:TYPE_STRING string_assign_op EOS\n");;
    break;}
case 63:
#line 120 "my_YACC.y"
{printf("string_assign_op:ID BSI exp ESI \n");;
    break;}
case 64:
#line 121 "my_YACC.y"
{printf("string_assign_op:ID BSI exp ESI COMMA string_assign_op \n");;
    break;}
case 65:
#line 122 "my_YACC.y"
{printf("string_assign_op:ID BSI exp ESI EQUAL string \n");;
    break;}
case 66:
#line 123 "my_YACC.y"
{printf("string_assign_op:ID BSI exp ESI EQUAL string COMMA string_assign_op \n");;
    break;}
case 67:
#line 126 "my_YACC.y"
{printf("premitive_assign_op:ID\n");;
    break;}
case 68:
#line 127 "my_YACC.y"
{printf("premitive_assign_op:ID COMMApremitive_assign_op \n");;
    break;}
case 69:
#line 128 "my_YACC.y"
{printf("premitive_assign_op:ID EQUAL exp \n");;
    break;}
case 70:
#line 129 "my_YACC.y"
{printf("premitive_assign_op:ID EQUAL exp COMMA premitive_assign_op \n");;
    break;}
case 73:
#line 137 "my_YACC.y"
{printf("block:SCB body ECB");;
    break;}
case 74:
#line 138 "my_YACC.y"
{printf("block:SCB body ECB");;
    break;}
case 76:
#line 142 "my_YACC.y"
{printf("(TYPE__INT)\n");;
    break;}
case 77:
#line 143 "my_YACC.y"
{printf("(TYPE__CHAR)\n");
    break;}
case 78:
#line 144 "my_YACC.y"
{printf("(TYPE__REAL)\n");;
    break;}
case 79:
#line 145 "my_YACC.y"
{printf("(TYPE__BOOL)\n");;
    break;}
case 80:
#line 146 "my_YACC.y"
{printf("(TYPE__INT*)\n");;
    break;}
case 81:
#line 147 "my_YACC.y"
{printf("(TYPE__char*)\n");;
    break;}
case 82:
#line 148 "my_YACC.y"
{printf("(TYPE__REAL*)\n");;
    break;}
case 83:
#line 150 "my_YACC.y"
{printf("func_body body\n");;
    break;}
case 89:
#line 163 "my_YACC.y"
{printf("body_:ifelse\n");
    break;}
case 90:
#line 164 "my_YACC.y"
{printf("body_:loop\n");
    break;}
case 91:
#line 165 "my_YACC.y"
{printf("body_:function\n");
    break;}
case 92:
#line 166 "my_YACC.y"
{printf("body_:void_function\n");
    break;}
case 93:
#line 167 "my_YACC.y"
{printf("body_:function_call\n");
    break;}
case 95:
#line 169 "my_YACC.y"
{printf("block:SCB body ECB");;
    break;}
case 96:
#line 171 "my_YACC.y"
{printf("function_call:ID LP RP \n");;
    break;}
case 97:
#line 172 "my_YACC.y"
{printf("function_call:ID LP exp_list RP \n");;
    break;}
case 98:
#line 174 "my_YACC.y"
{pritnf("exp_list:exp\n");;
    break;}
case 99:
#line 175 "my_YACC.y"
{printf("exp_list:exp_list COMMA exp");;
    break;}
case 100:
#line 178 "my_YACC.y"
{printf("if:IF LP exp RP SCB body ECB \n");;
    break;}
case 102:
#line 183 "my_YACC.y"
{printf("i'm while loop\n");;
    break;}
case 103:
#line 184 "my_YACC.y"
{printf("loop: for_loop\n");;
    break;}
case 104:
#line 185 "my_YACC.y"
{printf("loop:DO SCB body ECB WHILE LP exp RP EOS\n");;
    break;}
case 106:
#line 189 "my_YACC.y"
{printf("i++\n");;
    break;}
case 107:
#line 190 "my_YACC.y"
{printf("++i\n");;
    break;}
case 108:
#line 191 "my_YACC.y"
{printf("i--\n");;
    break;}
case 109:
#line 192 "my_YACC.y"
{printf("--i\n");;
    break;}
case 110:
#line 194 "my_YACC.y"
{printf("loop_i_dec: INT ID EQUAL DEC_INT\n");;
    break;}
case 111:
#line 195 "my_YACC.y"
{printf("loop_i_dec:ID EQUAL DEC_INT\n");;
    break;}
case 112:
#line 196 "my_YACC.y"
{printf("loop_i_dec: ID\n");;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 198 "my_YACC.y"
